#!/usr/bin/env bash
# Regenerates deploy/startup-script.sh, embedding the current app code
# (app.py, models.py, requirements.txt, templates/, static/) as a base64
# tarball. Run this locally whenever the app changes, then redeploy with
# the commands in deploy/README.md.
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

TMP_TAR="$(mktemp)"
tar czf "$TMP_TAR" app.py models.py requirements.txt templates static
B64="$(base64 -w0 "$TMP_TAR")"
rm -f "$TMP_TAR"

cat > deploy/startup-script.sh <<HEADER
#!/bin/bash
# Auto-generated by deploy/build.sh -- do not edit by hand.
# Runs on every VM boot. Safe to re-run: re-extracts app code but never
# touches inventory.db or the persisted SECRET_KEY.
set -e
APP_DIR=/opt/toolinventory
mkdir -p "\$APP_DIR"

base64 -d <<'APP_TARBALL_B64' | tar xz -C "\$APP_DIR"
$B64
APP_TARBALL_B64

apt-get update -y
apt-get install -y python3-venv python3-pip

if [ ! -d "\$APP_DIR/venv" ]; then
  python3 -m venv "\$APP_DIR/venv"
fi
"\$APP_DIR/venv/bin/pip" install -q --upgrade pip
"\$APP_DIR/venv/bin/pip" install -q -r "\$APP_DIR/requirements.txt"

# SHOP_PASSWORD comes from instance metadata (set/updated without touching code).
# SECRET_KEY is generated once and persisted so login sessions survive restarts.
ENV_FILE="\$APP_DIR/.env"
SHOP_PASSWORD_FROM_METADATA=\$(curl -s -H "Metadata-Flavor: Google" \\
  "http://metadata.google.internal/computeMetadata/v1/instance/attributes/shop-password" || true)

if [ ! -f "\$ENV_FILE" ]; then
  SECRET_KEY=\$(python3 -c "import secrets; print(secrets.token_hex(32))")
  {
    echo "SECRET_KEY=\$SECRET_KEY"
    echo "SHOP_PASSWORD=\$SHOP_PASSWORD_FROM_METADATA"
  } > "\$ENV_FILE"
else
  sed -i "/^SHOP_PASSWORD=/d" "\$ENV_FILE"
  echo "SHOP_PASSWORD=\$SHOP_PASSWORD_FROM_METADATA" >> "\$ENV_FILE"
fi

chown -R www-data:www-data "\$APP_DIR"
chmod 600 "\$ENV_FILE"

cat > /etc/systemd/system/toolinventory.service <<'UNIT'
[Unit]
Description=Shop Tool Inventory (Flask/Gunicorn)
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/opt/toolinventory
EnvironmentFile=/opt/toolinventory/.env
ExecStart=/opt/toolinventory/venv/bin/gunicorn --bind 0.0.0.0:8080 --workers 2 app:app
Restart=always

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable toolinventory
systemctl restart toolinventory
HEADER

echo "Wrote deploy/startup-script.sh ($(wc -c < deploy/startup-script.sh) bytes)"
